import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Notable, Limelight, Lacquer, Monoton } from "next/font/google";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navbar from "./components/Navbar";
import ScrollSmoother from "./components/ScrollSmoother";
import Preloader from "./components/Preloader";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const notable = Notable({
  variable: "--font-notable",
  weight: "400",
  subsets: ["latin"],
});

const limelight = Limelight({
  variable: "--font-limelight",
  weight: "400",
  subsets: ["latin"],
});

const lacquer = Lacquer({
  variable: "--font-lacquer",
  weight: "400",
  subsets: ["latin"],
});

const monoton = Monoton({
  variable: "--font-monoton",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dont Be Dumb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable} ${notable.variable} ${limelight.variable} ${lacquer.variable} ${monoton.variable} antialiased`}
      >
        <Preloader />
        <Navbar />
        <ScrollSmoother>
          {children}
        </ScrollSmoother>
      </body>

    </html>
  );
}
